server:
 servlet:
   context-path: /cliente-pet/api
   
 spring:
   datasource:
     url: jdbc:h2:men:demodb
     username: sa
     password:
     driverClasseName: org.h2.driver
       
   h2:
     console:
       enabled: true
       path: /h2-console